VERSION ?= $(shell git describe --tags --always 2>/dev/null || echo dev)
BIN     ?= $(HOME)/.local/bin/ternly

install:            ## build a static, stripped binary into ~/.local/bin
	go mod tidy
	CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.version=$(VERSION)" -o $(BIN) .
	@echo "installed $(BIN)"

test:
	go vet ./... && go test -race ./...

.PHONY: install test licenses

# THIRD_PARTY_LICENSES: the license texts of every linked module (go install github.com/google/go-licenses/v2@latest)
licenses:
	{ printf 'Third-party licenses of the Go modules linked into the ternly binary.\nGenerated by `make licenses` (go-licenses); the grammar notices are in NOTICE.\n'; \
	  go-licenses report . --template packaging/licenses.tpl --ignore github.com/rajasatyajit/ternly 2>/dev/null; } > THIRD_PARTY_LICENSES
